### ISSUE TITLE
Is Alea relied on cuDNN 5.1?

### ISSUE THREAD

**Issue by D-Walter** [Sergio0694/NeuralNetwork.NET#83]
I can not run the project DigitsCudaTest, error thrown noticed that 'Couldn't open CUDA library 'cudnn64_5''
Should i use cuDNN 5.1 or cuDNN 5.0 with CUDA 8.0?

**Comment by Sergio0694** [comment]
Hello, thank you for your interest in this project 😊
So far I've tested Alea with CUDA 9.0, and it looks like the best way to avoid issues is to just stick to the default `cudnn64_5.dll` file, as the `64_7` dll isn's properly supported yet (this is really up to the Alea developers, you can see I've opened a SO question [here](https://stackoverflow.com/questions/47824559/unable-to-use-cudnn-cudnn64-7-dll-file-with-alea-gpu-it-keeps-looking-for-the-o))

In order to run the library, make sure to:

- Install CUDA 9.0
- Set the `ALEA_CUDA_VERSION` set to `9.0` in the system environment variables (see [here](http://www.aleagpu.com/release/3_0_4/doc/faq.html#config_cuda_version))
- Set the `CUDA_PATH` environment variable to the CUDA folder on your system. It should be something like: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0`
- Download the `cudnn64_5.dll` file from NVIDIA and paste it in the `bin` folder of the `CUDA\v9.0` directory, Alea will load it from there

Let me know if that works for you!

**Comment by D-Walter** [comment]
It works after I stick 64_5.dll. Thanks for your help!

**Comment by D-Walter** [comment]
I'm so sorry to disturb you again.

Though it works properly but i cannot handle the exceptions `System.OutOfMemoryException` noticed me that `The array dimension exceeds the range of support` at `Alea.IL.Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)`.
It seems not fatal because it still keeps running, but i am worried whether it may cause some potential error.

Thanks for your patience.

P.S. I still use the origin project `DigitsCudaTest`

**Comment by Sergio0694** [comment]
No worries, happy to help!
If you get that error when starting the training, and then everything works fine (ie. if that only happens when the GPU kernels are JIT-compiled for the first time), then that's a known bug with Alea, when compiling the project using Visual Studio 17.

I've already contacted the Alea developers about that, they said it's caused by a change in the way Visual Studio handles .pdb files, which was changed from VS15 to VS17.
Anyways, that shouldn't cause any issues, and you can only see that if you directly reference the library project. That is, that error is visible for you because you're using the sample project, which has a link to the library project in the same solution, but if you create a new project in a new solution, and use the NuGet version of the NeuralNetwork.NET library, that error should not be visible at all 👍

**Comment by D-Walter** [comment]
Thx a lot, i got it
