### ISSUE TITLE
Which version of cuDNN should I install?

### ISSUE THREAD

**Issue by gundone** [Sergio0694/NeuralNetwork.NET#86]
Hello! I'm really intrested in your project. I read the thread #83 which says that the solution should work with cudnn64_5.dll. But all of I found [here](https://developer.nvidia.com/rdp/cudnn-archive) for cuda9 contains cudnn64_7.dll (for win10, or even win7). Where can I find properly versions of cuda and cudnn?

**Comment by Sergio0694** [comment]
Hi, thank you for your interested in the project 😄
You're right, I'm not finding cuDNN 5.x for CUDA 9.0 on that page, I'm not sure if they've removed it though (that'd be unexpected) or if I had been using the cuDNN 5.0 for CUDA 8.0 lib, with CUDA 9.0 instead.

You might try that (get the `cudnn64_5.dll` from the cuDNN 5.0 for CUDA 8.0 package) and combine it with CUDA 9.0, or if that fails, downgrade to CUDA 8.0 for the time being (so that the cuDNN 5.0 lib will work fine for sure).

I haven't been able to get the AleaGPU lib working with more recent versions of CUDA/cuDNN unfortunately, and due to lack of time and no reply from the devs I gave up on that at least for now.

Let me know if using cuDNN 5.0 and CUDA 8.0/9.0 works for you!

**Comment by Sergio0694** [comment]
Closing for lack of reply from OP.
