### ISSUE TITLE
Could not load file or assembly Alea when using CuDnnNetworkLayers

### ISSUE THREAD

**Issue by dariooo512** [Sergio0694/NeuralNetwork.NET#90]
## Expected Behavior
The instruction CuDnnNetworkLayers.IsCudaSupportAvailable should return True if Cuda is available, False otherwise 

## Current Behavior
Exception is raised:
System.IO.FileNotFoundException: 'Could not load file or assembly 'Alea, Version=3.0.0.0, Culture=neutral, PublicKeyToken=ba52afc3c2e933d6'.

Gym.NET/examples/AtariDeepQLearner/AtariDeepQLearner/Trainer.cs line 32

## Steps to Reproduce
1. Clone [this repo](https://github.com/dariooo512/Gym.NET/tree/dev) (branch: dev)
2. Go to folder examples/AtariDeepQLearner
3. Set AtariDeepQLearner.Runner as startup project
4. Run

**Comment by Sergio0694** [comment]
Hey @dariooo512 - sorry for the delay!
As stated in the readme, the CUDA support is only available on .NET Framework, not on .NET Core 3.0 unfortunately. The library I'm using for that (Alea.Gpu) is only available for .NET Framework.

If you're using the library in a .NET Core 3.0 project, you'll have to stick with the CPU APIs. I might eventually add GPU support on .NET Core 3.0 too through my other library `ComputeSharp`, though I don't have anything planned for the short term due to other work I have to do right now.

Hope this helps!
